import { useMemo } from 'react';
import { Plus, Trash2 } from 'lucide-react';
export default function InvoiceItems({ value, onChange }) {
  const rows=useMemo(()=>String(value||'Perkhidmatan | 1 | 100.00').split('\n').map(line=>{const [name='',quantity='1',price='0']=line.split('|');return {name:name.trim(),quantity:quantity.trim(),price:price.trim()};}),[value]);
  const save=next=>onChange(next.map(r=>`${r.name.replace(/[|\n]/g,' ')} | ${r.quantity} | ${r.price}`).join('\n'));
  const update=(i,key,v)=>save(rows.map((r,n)=>n===i?{...r,[key]:v}:r));
  const total=rows.reduce((sum,r)=>sum+(Number(r.quantity)||0)*(Number(r.price)||0),0);
  return <div className="mt-4 rounded-xl border p-4"><h2 className="font-bold">Item invois</h2><div className="mt-3 space-y-3">{rows.map((row,i)=><div key={i} className="grid grid-cols-12 items-end gap-2"><label className="col-span-12 text-sm sm:col-span-5">Perkara<input aria-label={`Perkara ${i+1}`} className="medan" value={row.name} onChange={e=>update(i,'name',e.target.value)}/></label><label className="col-span-3 text-sm sm:col-span-2">Kuantiti<input aria-label={`Kuantiti ${i+1}`} className="medan" type="number" min="0.01" step="0.01" value={row.quantity} onChange={e=>update(i,'quantity',e.target.value)}/></label><label className="col-span-5 text-sm sm:col-span-3">Harga (RM)<input aria-label={`Harga ${i+1}`} className="medan" type="number" min="0" step="0.01" value={row.price} onChange={e=>update(i,'price',e.target.value)}/></label><button type="button" aria-label={`Buang item ${i+1}`} className="col-span-4 flex justify-center p-3 text-red-700 sm:col-span-2" disabled={rows.length===1} onClick={()=>save(rows.filter((_,n)=>n!==i))}><Trash2 size={18}/></button></div>)}</div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><button type="button" className="btn-lembut text-sm" disabled={rows.length>=100} onClick={()=>save([...rows,{name:'Item baharu',quantity:'1',price:'0.00'}])}><Plus size={16}/>Tambah item</button><strong>Jumlah: RM {total.toFixed(2)}</strong></div></div>;
}
