import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {usePdfDocument} from './pdfPreview.js';
import {Thumbnail} from './PdfPages.jsx';
function Source({file,index,onReady}){const {doc,error}=usePdfDocument(file);const update=useRef(onReady);update.current=onReady;useEffect(()=>{if(doc)update.current(index,doc);},[doc,index]);return error?<p role="alert" className="text-red-700">{file.name}: {error}</p>:null;}
export default function PageOrganizer({files,value,onChange}){
 const [docs,setDocs]=useState({}),[pages,setPages]=useState([]),[batch,setBatch]=useState(0);const update=useRef(onChange);update.current=onChange;const previous=useRef(null);const counter=useRef(0);
 const fresh=item=>({...item,id:++counter.current});
 useLayoutEffect(()=>{setDocs({});setPages([]);setBatch(0);previous.current=null;update.current('[]');},[files]);
 const ready=(index,doc)=>{setDocs(s=>({...s,[index]:doc}));setPages(s=>{if(s.some(p=>p.fail===index))return s;return [...s,...Array.from({length:doc.numPages},(_,n)=>fresh({fail:index,halaman:n+1,putaran:0}))].sort((a,b)=>a.fail-b.fail||a.halaman-b.halaman);});};
 const readyAll=Object.keys(docs).length===files.length;
 useEffect(()=>{if(!readyAll){update.current('[]');return;}if(previous.current!==null||pages.length){const json=JSON.stringify(pages.map(({id,...p})=>p));previous.current=json;update.current(json);}},[pages,readyAll]);
 const move=(from,to)=>{if(to<0||to>=pages.length)return;setPages(s=>{const n=[...s];n.splice(to,0,n.splice(from,1)[0]);return n;});};
 const last=Math.max(0,Math.ceil(pages.length/20)-1);useEffect(()=>setBatch(s=>Math.min(s,last)),[last]);
 return <section className="mt-4 rounded-xl border p-4" aria-label="Urus halaman semua fail"><h2 className="font-bold">Gabung, salin, putar dan susun</h2><p className="mt-1 text-sm text-gray-500">Tambah semua PDF dahulu. Seret kad atau guna anak panah. Mengubah senarai fail akan menetapkan semula susunan.</p>{files.map((file,i)=><Source key={`${i}-${file.name}-${file.lastModified}`} file={file} index={i} onReady={ready}/>)}<p className="my-3 text-sm">{readyAll?`${pages.length} halaman dalam hasil`:'Memuatkan semua dokumen…'}</p><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{(readyAll?pages.slice(batch*20,batch*20+20):[]).map((item,local)=>{const i=batch*20+local;return <article key={item.id} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',String(i))} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const raw=e.dataTransfer.getData('text/plain');if(/^\d+$/.test(raw))move(Number(raw),i);}} className="rounded-lg border bg-gray-50 p-2"><div className="flex h-52 items-center justify-center bg-white">{docs[item.fail]&&<Thumbnail doc={docs[item.fail]} number={item.halaman} angle={item.putaran}/>}</div><p className="mt-2 truncate text-xs" title={files[item.fail]?.name}>{i+1}. {files[item.fail]?.name} · H{item.halaman}</p><div className="mt-2 flex flex-wrap gap-1"><button className="btn-lembut !p-2" type="button" disabled={i===0} aria-label={`Alih kad ${i+1} ke kiri`} onClick={()=>move(i,i-1)}>←</button><button className="btn-lembut !p-2" type="button" disabled={i===pages.length-1} aria-label={`Alih kad ${i+1} ke kanan`} onClick={()=>move(i,i+1)}>→</button><button className="btn-lembut !p-2" type="button" aria-label={`Putar kad ${i+1}`} onClick={()=>setPages(s=>s.map(p=>p.id===item.id?{...p,putaran:(p.putaran+90)%360}:p))}>↻</button><button className="btn-lembut !p-2" type="button" aria-label={`Salin kad ${i+1}`} onClick={()=>setPages(s=>[...s.slice(0,i+1),fresh(item),...s.slice(i+1)])}>Salin</button><button className="btn-lembut !p-2 text-red-700" type="button" aria-label={`Padam kad ${i+1}`} onClick={()=>setPages(s=>s.filter(p=>p.id!==item.id))}>Padam</button></div></article>;})}</div>{last>0&&<div className="mt-4 flex items-center justify-between"><button className="btn-lembut" disabled={batch===0} onClick={()=>setBatch(batch-1)}>Sebelum</button><span>{batch+1}/{last+1}</span><button className="btn-lembut" disabled={batch===last} onClick={()=>setBatch(batch+1)}>Seterusnya</button></div>}</section>;
}
