import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {useState} from 'react';
import {MemoryRouter,Routes,Route} from 'react-router-dom';
import PageOrganizer from './PageOrganizer.jsx';
import CameraScan from './CameraScan.jsx';
import {WorkflowControls,BatchControls,FindPreview} from './UpgradeControls.jsx';
import ToolPage from '../pages/ToolPage.jsx';
import {api} from '../services/api.js';
const mocks=vi.hoisted(()=>({doc:{numPages:2,getPage:vi.fn(async()=>({rotate:0,getViewport:({scale})=>({width:600*scale,height:800*scale,convertToViewportRectangle:r=>r}),getAnnotations:async()=>[],render:()=>({promise:Promise.resolve(),cancel:()=>{}})}))},toast:{berjaya:vi.fn(),ralat:vi.fn()}}));
vi.mock('./pdfPreview.js',()=>({usePdfDocument:()=>({doc:mocks.doc,error:''})}));
vi.mock('../services/api.js',()=>({api:{periksaPdf:vi.fn(),proses:vi.fn(),fullUrl:u=>u}}));
vi.mock('./Toast.jsx',()=>({useToast:()=>mocks.toast}));
const files=[new File(['pdf'],'A.pdf',{type:'application/pdf'}),new File(['pdf'],'B.pdf',{type:'application/pdf'})];
function Organizer(){const[value,setValue]=useState('[]');return <><PageOrganizer files={files} value={value} onChange={setValue}/><output data-testid="value">{value}</output></>;}
function Workflow(){const[value,setValue]=useState();return <><WorkflowControls value={value} onChange={setValue}/><output data-testid="value">{value}</output></>;}
function Batch(){const[value,setValue]=useState({});return <><BatchControls value={value} onChange={setValue}/><output data-testid="value">{JSON.stringify(value)}</output></>;}
function Scan(){const[value,setValue]=useState();return <><CameraScan files={[new File(['image'],'scan.jpg',{type:'image/jpeg'})]} onFiles={()=>{}} value={value} onChange={setValue}/><output data-testid="value">{value}</output></>;}
beforeEach(()=>{vi.clearAllMocks();localStorage.clear();URL.createObjectURL=vi.fn(()=> 'blob:hasil');URL.revokeObjectURL=vi.fn();vi.spyOn(HTMLCanvasElement.prototype,'getContext').mockReturnValue({fillRect:()=>{}});vi.spyOn(HTMLElement.prototype,'getBoundingClientRect').mockReturnValue({left:0,top:0,width:500,height:650});});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});
describe('kawalan sepuluh naik taraf',()=>{
 it('halaman beberapa fail boleh disalin, diputar, dipadam dan dialih',async()=>{render(<Organizer/>);await screen.findByRole('button',{name:'Salin kad 4'});await userEvent.click(screen.getByRole('button',{name:'Salin kad 1'}));await userEvent.click(screen.getByRole('button',{name:'Putar kad 2'}));await userEvent.click(screen.getByRole('button',{name:'Alih kad 2 ke kanan'}));await userEvent.click(screen.getByRole('button',{name:'Padam kad 1'}));const data=JSON.parse(screen.getByTestId('value').textContent);expect(data).toHaveLength(4);expect(data[1].putaran).toBe(90);expect(data[3].fail).toBe(1);});
 it('preset aliran kerja disimpan dan boleh digunakan semula',async()=>{render(<Workflow/>);await userEvent.click(screen.getByRole('button',{name:/Preset OCR/}));await userEvent.click(screen.getByRole('button',{name:'Simpan tetapan'}));expect(JSON.parse(localStorage.getItem('sbp_workflow'))).toHaveLength(3);await userEvent.click(screen.getByRole('button',{name:'Buang langkah 1'}));expect(JSON.parse(screen.getByTestId('value').textContent)).toHaveLength(2);await userEvent.click(screen.getByRole('button',{name:'Guna tetapan disimpan'}));expect(JSON.parse(screen.getByTestId('value').textContent)[0].slug).toBe('ocr-pdf');});
 it('pilihan kelompok menggunakan tetapan alat terpilih',async()=>{render(<Batch/>);await userEvent.selectOptions(screen.getByLabelText('Alat'),'pdf-ke-word');expect(screen.getByLabelText('Cara penukaran')).toBeTruthy();expect(JSON.parse(screen.getByTestId('value').textContent).alat_batch).toBe('pdf-ke-word');});
 it('scan menyimpan empat penjuru dan reset',async()=>{render(<Scan/>);const img=await screen.findByAltText('Gambar untuk scan');for(const[x,y]of[[50,60],[450,60],[450,600],[50,600]])fireEvent.click(img,{clientX:x,clientY:y});expect(JSON.parse(screen.getByTestId('value').textContent)[0]).toHaveLength(4);await userEvent.click(screen.getByRole('button',{name:'Reset penjuru gambar ini'}));expect(screen.getByTestId('value').textContent).toBe('{}');});
 it('preview carian memaparkan jumlah serta halaman padanan',async()=>{api.periksaPdf.mockResolvedValue({jumlah:1,padanan:[{halaman:2,baris:'Ali makan'}]});render(<FindPreview file={files[0]} value={{cari:'Ali',seluruh:'ya'}}/>);await userEvent.click(screen.getByRole('button',{name:'Semak padanan sebelum ganti'}));expect(await screen.findByText('1 padanan')).toBeTruthy();expect(screen.getByText('H2: Ali makan')).toBeTruthy();});
 it('hasil PDF dipindahkan ke alat lain tanpa memilih fail lagi',async()=>{api.proses.mockResolvedValue({muat_turun:'/hasil',nama_fail:'kecil.pdf',nota:'Sasaran saiz berjaya dicapai.'});vi.stubGlobal('fetch',vi.fn(async()=>({ok:true,blob:async()=>new Blob(['%PDF'],{type:'application/pdf'})})));render(<MemoryRouter initialEntries={[{pathname:'/alat/mampat-sasaran',state:{document:files[0]}}]}><Routes><Route path="/alat/:slug" element={<ToolPage/>}/></Routes></MemoryRouter>);await userEvent.click(await screen.findByRole('button',{name:'Mampat Ikut Saiz'}));await screen.findByText('Sasaran saiz berjaya dicapai.');await userEvent.selectOptions(screen.getByLabelText('Alat seterusnya'),'pdf-ke-teks');await userEvent.click(screen.getByRole('button',{name:'Sambung tanpa pilih fail semula'}));expect(await screen.findByText('kecil.pdf')).toBeTruthy();await userEvent.click(screen.getByRole('button',{name:'PDF kepada Teks'}));await waitFor(()=>expect(api.proses).toHaveBeenCalledTimes(2));expect(api.proses.mock.calls[1][1][0].name).toBe('kecil.pdf');});
 it('AI tidak dihantar apabila persetujuan belum ditandakan',async()=>{render(<MemoryRouter initialEntries={[{pathname:'/alat/ai-pdf',state:{document:files[0]}}]}><Routes><Route path="/alat/:slug" element={<ToolPage/>}/></Routes></MemoryRouter>);await userEvent.click(await screen.findByRole('button',{name:'AI untuk PDF'}));expect(await screen.findByText('Tandakan persetujuan penggunaan AI dahulu.')).toBeTruthy();expect(api.proses).not.toHaveBeenCalled();});
});
