import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {useState} from 'react';
import {MemoryRouter,Routes,Route} from 'react-router-dom';
import PageOrganizer from './PageOrganizer.jsx';
import CameraScan,{validCorners} from './CameraScan.jsx';
import {WorkflowControls,BatchControls,FindPreview} from './UpgradeControls.jsx';
import ToolPage from '../pages/ToolPage.jsx';
import {api} from '../services/api.js';
const mocks=vi.hoisted(()=>({doc:{numPages:2,getPage:vi.fn(async()=>({rotate:0,getViewport:({scale})=>({width:600*scale,height:800*scale,convertToViewportRectangle:r=>r}),getAnnotations:async()=>[],render:()=>({promise:Promise.resolve(),cancel:()=>{}})}))},toast:{berjaya:vi.fn(),ralat:vi.fn()}}));
vi.mock('./pdfPreview.js',()=>({usePdfDocument:()=>({doc:mocks.doc,error:''})}));
vi.mock('../services/api.js',()=>({api:{periksaPdf:vi.fn(),proses:vi.fn(),fullUrl:u=>u}}));
vi.mock('./Toast.jsx',()=>({useToast:()=>mocks.toast}));
const files=[new File(['pdf'],'A.pdf',{type:'application/pdf'}),new File(['pdf'],'B.pdf',{type:'application/pdf'})];
function Organizer(){const[value,setValue]=useState('[]');return <><PageOrganizer files={files} value={value} onChange={setValue}/><output data-testid="value">{value}</output></>;}
function Workflow(){const[value,setValue]=useState();return <><WorkflowControls value={value} onChange={setValue}/><output data-testid="value">{value}</output></>;}
function Batch(){const[value,setValue]=useState({});return <><BatchControls value={value} onChange={setValue}/><output data-testid="value">{JSON.stringify(value)}</output></>;}
const scanFile=new File(['image'],'scan.jpg',{type:'image/jpeg'});
function Scan(){const[value,setValue]=useState();return <><CameraScan files={[scanFile]} onFiles={()=>{}} value={value} onChange={setValue}/><output data-testid="value">{value}</output></>;}
beforeEach(()=>{vi.clearAllMocks();api.periksaPdf.mockReset();vi.stubGlobal('PointerEvent',MouseEvent);localStorage.clear();URL.createObjectURL=vi.fn(()=> 'blob:hasil');URL.revokeObjectURL=vi.fn();vi.spyOn(HTMLCanvasElement.prototype,'getContext').mockReturnValue({fillRect:()=>{}});vi.spyOn(HTMLElement.prototype,'getBoundingClientRect').mockReturnValue({left:0,top:0,width:500,height:650});});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});
describe('kawalan sepuluh naik taraf',()=>{
 it('halaman beberapa fail boleh disalin, diputar, dipadam dan dialih',async()=>{render(<Organizer/>);await screen.findByRole('button',{name:'Salin kad 4'});await userEvent.click(screen.getByRole('button',{name:'Salin kad 1'}));await userEvent.click(screen.getByRole('button',{name:'Putar kad 2'}));await userEvent.click(screen.getByRole('button',{name:'Alih kad 2 ke kanan'}));await userEvent.click(screen.getByRole('button',{name:'Padam kad 1'}));const data=JSON.parse(screen.getByTestId('value').textContent);expect(data).toHaveLength(4);expect(data[1].putaran).toBe(90);expect(data[3].fail).toBe(1);});
 it('preset aliran kerja disimpan dan boleh digunakan semula',async()=>{render(<Workflow/>);await userEvent.click(screen.getByRole('button',{name:/Preset OCR/}));await userEvent.click(screen.getByRole('button',{name:'Simpan tetapan'}));expect(JSON.parse(localStorage.getItem('sbp_workflow'))).toHaveLength(3);await userEvent.click(screen.getByRole('button',{name:'Buang langkah 1'}));expect(JSON.parse(screen.getByTestId('value').textContent)).toHaveLength(2);await userEvent.click(screen.getByRole('button',{name:'Guna tetapan disimpan'}));expect(JSON.parse(screen.getByTestId('value').textContent)[0].slug).toBe('ocr-pdf');});
 it('pilihan kelompok menggunakan tetapan alat terpilih',async()=>{render(<Batch/>);await userEvent.selectOptions(screen.getByLabelText('Alat'),'pdf-ke-word');expect(screen.getByLabelText('Cara penukaran')).toBeTruthy();expect(JSON.parse(screen.getByTestId('value').textContent).alat_batch).toBe('pdf-ke-word');});
 it('scan menyediakan empat pemegang, drag dan kanta pembesar tanpa klik urutan',async()=>{render(<Scan/>);await screen.findByAltText('Gambar untuk scan');await waitFor(()=>expect(screen.getByRole('button',{name:'Kesan tepi automatik'}).disabled).toBe(false));const handle=screen.getByRole('button',{name:'Penjuru atas kiri'});fireEvent.pointerDown(handle,{clientX:30,clientY:39,button:0});expect(screen.getByRole('img',{name:'Kanta pembesar penjuru'})).toBeTruthy();fireEvent.pointerMove(handle,{clientX:50,clientY:65});fireEvent.pointerUp(handle);expect(JSON.parse(screen.getByTestId('value').textContent)[0][0]).toEqual({x:10,y:10});expect(screen.queryByRole('img',{name:'Kanta pembesar penjuru'})).toBeNull();await userEvent.click(screen.getByRole('button',{name:'Reset penjuru gambar ini'}));expect(JSON.parse(screen.getByTestId('value').textContent)[0][0]).toEqual({x:6,y:6});});
 it('penjuru bersilang, kawasan kecil dan koordinat tidak sah dihalang',()=>{expect(validCorners([{x:10,y:10},{x:90,y:10},{x:90,y:90},{x:10,y:90}])).toBe(true);expect(validCorners([{x:95,y:95},{x:90,y:10},{x:90,y:90},{x:10,y:90}])).toBe(false);expect(validCorners([{x:10,y:10},{x:11,y:10},{x:11,y:11},{x:10,y:11}])).toBe(false);expect(validCorners([{x:NaN,y:0}])).toBe(false);});
 it('auto tepi disimpan dan preview menggunakan penjuru yang dilaras',async()=>{const corners=[{x:12,y:9},{x:84,y:5},{x:92,y:91},{x:8,y:95}];api.periksaPdf.mockResolvedValue({penjuru:corners,dikesan:true,pratonton:'data:image/jpeg;base64,abc'});render(<Scan/>);await screen.findByText(/Tepi kertas dikesan/);expect(JSON.parse(screen.getByTestId('value').textContent)[0]).toEqual(corners);fireEvent.keyDown(screen.getByRole('button',{name:'Penjuru atas kiri'}),{key:'ArrowRight'});await userEvent.click(screen.getByRole('button',{name:'Pratonton crop'}));expect(await screen.findByAltText('Pratonton kertas selepas crop')).toBeTruthy();expect(JSON.parse(api.periksaPdf.mock.calls[1][4].penjuru)[0].x).toBe(12.5);fireEvent.keyDown(screen.getByRole('button',{name:'Penjuru atas kiri'}),{key:'ArrowRight'});expect(screen.queryByAltText('Pratonton kertas selepas crop')).toBeNull();});
 it('respons auto lambat tidak menimpa pelarasan pengguna',async()=>{let resolve;api.periksaPdf.mockReturnValue(new Promise(r=>{resolve=r;}));render(<Scan/>);await screen.findByAltText('Gambar untuk scan');fireEvent.keyDown(screen.getByRole('button',{name:'Penjuru atas kiri'}),{key:'ArrowRight'});resolve({penjuru:[{x:10,y:10},{x:90,y:10},{x:90,y:90},{x:10,y:90}],dikesan:true});await waitFor(()=>expect(JSON.parse(screen.getByTestId('value').textContent)[0][0].x).toBe(6.5));});
 it('preview carian memaparkan jumlah serta halaman padanan',async()=>{api.periksaPdf.mockResolvedValue({jumlah:1,padanan:[{halaman:2,baris:'Ali makan'}]});render(<FindPreview file={files[0]} value={{cari:'Ali',seluruh:'ya'}}/>);await userEvent.click(screen.getByRole('button',{name:'Semak padanan sebelum ganti'}));expect(await screen.findByText('1 padanan')).toBeTruthy();expect(screen.getByText('H2: Ali makan')).toBeTruthy();});
 it('hasil PDF dipindahkan ke alat lain tanpa memilih fail lagi',async()=>{api.proses.mockResolvedValue({muat_turun:'/hasil',nama_fail:'kecil.pdf',nota:'Sasaran saiz berjaya dicapai.'});vi.stubGlobal('fetch',vi.fn(async()=>({ok:true,blob:async()=>new Blob(['%PDF'],{type:'application/pdf'})})));render(<MemoryRouter initialEntries={[{pathname:'/alat/mampat-sasaran',state:{document:files[0]}}]}><Routes><Route path="/alat/:slug" element={<ToolPage/>}/></Routes></MemoryRouter>);await userEvent.click(await screen.findByRole('button',{name:'Mampat Ikut Saiz'}));await screen.findByText('Sasaran saiz berjaya dicapai.');await userEvent.selectOptions(screen.getByLabelText('Alat seterusnya'),'pdf-ke-teks');await userEvent.click(screen.getByRole('button',{name:'Sambung tanpa pilih fail semula'}));expect(await screen.findByText('kecil.pdf')).toBeTruthy();await userEvent.click(screen.getByRole('button',{name:'PDF kepada Teks'}));await waitFor(()=>expect(api.proses).toHaveBeenCalledTimes(2));expect(api.proses.mock.calls[1][1][0].name).toBe('kecil.pdf');});
 it('AI tidak dihantar apabila persetujuan belum ditandakan',async()=>{render(<MemoryRouter initialEntries={[{pathname:'/alat/ai-pdf',state:{document:files[0]}}]}><Routes><Route path="/alat/:slug" element={<ToolPage/>}/></Routes></MemoryRouter>);await userEvent.click(await screen.findByRole('button',{name:'AI untuk PDF'}));expect(await screen.findByText('Tandakan persetujuan penggunaan AI dahulu.')).toBeTruthy();expect(api.proses).not.toHaveBeenCalled();});
});
